swagger: "2.0"

info:
  version: 1.0.0
  title: Phonebook API
  description: An API for the Phonebook application

tags:
  - name: contact
    description: Everything about your Contacts

schemes:
  - http
host: localhost:3001
basePath: /

paths:
  /contacts:
    get:
      tags:
        - contact
      summary: Gets all contacts
      description: Returns a list of all contacts in the Phonebook.
      responses:
        200:
          description: A list of Contact objects
          schema:
            type: array
            items:
              properties:
                _id:
                  type: string
                  uniqueItems: true
                name:
                  type: string
                numbers:
                  type: array
                  items:
                    properties:
                      _id:
                        type: string
                      number:
                        type: string
                      description:
                        type: string
                      classification:
                        type: string
    post:
      tags:
        - contact
      summary: Adds a new contact
      description: Adds a new contact to the Phonebook.
      parameters:
        - in: body
          name: body
          description: Contact object that needs to be added to the Phonebook
          required: true
          schema:
            properties:
              name:
                type: string
              numbers:
                type: array
                items:
                  properties:
                    number:
                      type: string
                    description:
                      type: string
                    classification:
                      type: string
      responses:
        200:
          description: Contact added successfully
          schema:
            properties:
              _id:
                type: string
                uniqueItems: true
              name:
                type: string
              numbers:
                type: array
                items:
                  properties:
                    _id:
                      type: string
                    number:
                      type: string
                    description:
                      type: string
                    classification:
                      type: string
        500:
          description: Unable to add Contact
  /contacts/{id}:
    get:
      tags:
        - contact
      summary: Returns a single Contact
      description: Returns a single Contact from the Phonebook.
      parameters:
        - in: path
          name: id
          description: ID of Contact to return
          required: true
          type: string
      responses:
        200:
          description: Contract retrieved successfully
          schema:
            properties:
              _id:
                type: string
                uniqueItems: true
              name:
                type: string
              numbers:
                type: array
                items:
                  properties:
                    _id:
                      type: string
                    number:
                      type: string
                    description:
                      type: string
                    classification:
                      type: string
        500:
          description: Unable to find the Contact
    put:
      tags:
        - contact
      summary: Updates an existing Contact
      description: Updates an existing Contact in the Phonebook.
      parameters:
        - in: path
          name: id
          description: ID of Contact to update
          required: true
          type: string
        - in: body
          name: body
          description: Contact object that needs to be added to the Phonebook
          required: true
          schema:
            properties:
              name:
                type: string
              numbers:
                type: array
                items:
                  properties:
                    number:
                      type: string
                    description:
                      type: string
                    classification:
                      type: string
      responses:
        200:
          description: Contact updated successfully
          schema:
            properties:
              _id:
                type: string
                uniqueItems: true
              name:
                type: string
              numbers:
                type: array
                items:
                  properties:
                    _id:
                      type: string
                    number:
                      type: string
                    description:
                      type: string
                    classification:
                      type: string
        500:
          description: Unable to update the Contact
    delete:
      tags:
        - contact
      summary: Deletes a Contact
      description: Deletes a Contact from the Phonebook.
      parameters:
        - in: path
          name: id
          required: true
      responses:
        200:
          description: Contact successfully deleted
        500:
          description: Unable to delete Contact